import 'dotenv/config';
import { PrismaClient } from '../src/generated/prisma/client.js';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';
import bcrypt from 'bcryptjs';

const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
});

const adapter = new PrismaPg(pool);

const prisma = new PrismaClient({ adapter });

const IMG = (name: string) => `/assets/products/${name}`;

async function main() {
    console.log('Seeding database...');

    // ── Create Admin User ──
    // Production password should be changed via the app or database directly
    const adminPassword = await bcrypt.hash('TasmanStar!Seed2026#', 12);
    const admin = await prisma.user.upsert({
        where: { email: 'admin@tasmanstar.com.au' },
        update: {},
        create: {
            email: 'admin@tasmanstar.com.au',
            passwordHash: adminPassword,
            name: 'Admin',
            phone: '+61755290844',
            role: 'ADMIN',
        },
    });
    console.log(`Admin user: ${admin.email}`);

    // ── Delete existing products & categories (clean slate) ──
    await prisma.orderItem.deleteMany({});
    await prisma.order.deleteMany({});
    await prisma.product.deleteMany({});
    await prisma.category.deleteMany({});
    console.log('Cleared existing products & categories');

    // ── Create Categories ──
    const categories = [
        { name: 'Fish (Whole)', slug: 'fish-whole', imageUrl: IMG('local-snapper-whole.webp'), sortOrder: 1 },
        { name: 'Fish (Fillets & Steaks)', slug: 'fish-fillets-steaks', imageUrl: IMG('red-snapper-fillet.webp'), sortOrder: 2 },
        { name: 'Prawns (Cooked)', slug: 'prawns-cooked', imageUrl: IMG('large-cooked-king-prawn.webp'), sortOrder: 3 },
        { name: 'Prawns (Raw)', slug: 'prawns-raw', imageUrl: IMG('jumbo-raw-kung-prawns.webp'), sortOrder: 4 },
        { name: 'Live Seafood', slug: 'live-seafood', imageUrl: IMG('live-mud-crabs.webp'), sortOrder: 5 },
        { name: 'Crabs (Cooked)', slug: 'crabs-cooked', imageUrl: IMG('cooked-sand-crab.webp'), sortOrder: 6 },
        { name: 'Bugs, Lobsters & Crayfish', slug: 'bugs-lobsters-crayfish', imageUrl: IMG('large-cooked-moreton-bay-bugs.webp'), sortOrder: 7 },
        { name: 'Oysters', slug: 'oysters', imageUrl: IMG('pacific-plate-oyster.webp'), sortOrder: 8 },
        { name: 'Shellfish & Molluscs', slug: 'shellfish-molluscs', imageUrl: IMG('tasmania-scallops-meat.webp'), sortOrder: 9 },
        { name: 'Squid, Octopus & Cuttlefish', slug: 'squid-octopus-cuttlefish', imageUrl: IMG('cleaned-octoupus-2.webp'), sortOrder: 10 },
        { name: 'Prepared Meals', slug: 'prepared-meals', imageUrl: IMG('stir-fried-pre-made-meal.webp'), sortOrder: 11 },
        { name: 'Sushi', slug: 'sushi', imageUrl: IMG('sushi-nigiri-set.webp'), sortOrder: 12 },
        { name: 'Sashimi', slug: 'sashimi', imageUrl: IMG('sashimi-platter.webp'), sortOrder: 13 },
        { name: 'Frozen Traded', slug: 'frozen-traded', imageUrl: IMG('frozen-lobster-meat.webp'), sortOrder: 14 },
        { name: 'Sauces, Condiments & Packaged Goods', slug: 'sauces-condiments-packaged', imageUrl: IMG('img3304.webp'), sortOrder: 15 },
    ];

    const categoryMap: Record<string, string> = {};
    for (const cat of categories) {
        const created = await prisma.category.create({ data: cat });
        categoryMap[cat.slug] = created.id;
    }
    console.log(`Created ${categories.length} categories`);

    // ── Create Products ──
    type ProductInput = {
        name: string;
        slug: string;
        price: number;
        categorySlug: string;
        imageUrls: string[];
        unit: 'KG' | 'PIECE' | 'DOZEN' | 'BOX' | 'PACK';
        tags: string[];
        isFeatured?: boolean;
        isTodaysSpecial?: boolean;
        description?: string;
        countryOfOrigin?: string;
    };

    const products: ProductInput[] = [
        // ═══════════════════════════════════════
        // FISH (WHOLE)
        // ═══════════════════════════════════════
        {
            name: 'Alfonsino Whole',
            slug: 'alfonsino-whole',
            price: 28.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('alfonsino-whole.webp'), IMG('alfonsina-whole.webp'), IMG('alfonsino.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole alfonsino — a premium deep-water species with bright red skin and tender, flavourful white flesh. Excellent roasted whole with herbs and citrus.',
        },
        {
            name: 'Big Eye Tuna',
            slug: 'big-eye-tuna',
            price: 42.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('big-eye-tuna.webp'), IMG('big-eye-tuna-2.webp')],
            unit: 'KG',
            tags: [],
            description: 'Big eye tuna — deep ruby-red flesh with rich, meaty flavour and buttery texture. A premium species perfect for searing or sashimi. Sold per kg from Tasman Star Seafoods.',
        },
        {
            name: 'Blue Cod',
            slug: 'blue-cod',
            price: 45.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('blue-code-gg.webp'), IMG('blue-cod-whole-2.webp')],
            unit: 'KG',
            tags: [],
            description: 'Blue cod — a highly regarded New Zealand species with firm, white flesh and a clean, sweet flavour. Excellent pan-fried or battered.',
        },
        {
            name: 'Blue Mackerel Whole',
            slug: 'blue-mackerel-whole',
            price: 18.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('blue-mackeral-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole blue mackerel — an oily, omega-3 rich fish with bold flavour. Great grilled, smoked or barbecued. Affordable and nutritious from Tasman Star Seafoods.',
        },
        {
            name: 'Coral Trout Whole',
            slug: 'coral-trout-whole',
            price: 60.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('coraltrout-whole.webp'), IMG('coral-trout-whole-2.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole coral trout — one of Queensland\'s most prized reef fish with delicate, sweet white flesh. Wild caught and perfect for steaming or baking whole.',
        },
        {
            name: 'Fresh Sardines',
            slug: 'fresh-sardines',
            price: 12.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('frsh-sardines-2.webp'), IMG('sardine-fresh-2.webp'), IMG('sardines-fresh.webp')],
            unit: 'KG',
            tags: [],
            description: 'Fresh sardines — small, flavourful fish packed with omega-3s. Grill whole with olive oil and lemon for a simple Mediterranean treat. Great value from Tasman Star Seafoods.',
        },
        {
            name: 'Goat Fish Whole',
            slug: 'goat-fish-whole',
            price: 22.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('goat-fish-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole goat fish — a colourful reef species with mild, sweet flesh. Popular in Mediterranean and Asian cuisines, excellent pan-fried or grilled.',
        },
        {
            name: 'Gold Band Snapper Whole',
            slug: 'gold-band-snapper-whole',
            price: 55.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('gold-band-snapper-whole.webp'), IMG('gold-band-snapper-whole-2.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole gold band snapper — a premium deep-water snapper with firm, moist flesh and a delicate flavour. Perfect for roasting whole or filleting at home.',
        },
        {
            name: 'Hardy Heads Whole',
            slug: 'hardy-heads-whole',
            price: 15.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('hardy-heads-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole hardy heads — small baitfish perfect for deep-frying whole as a crispy snack or used as premium fishing bait. Affordable and fresh from the Gold Coast.',
        },
        {
            name: 'Hiramasa Kingfish Whole',
            slug: 'hiramasa-kingfish-whole',
            price: 42.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('hira-masa-king-fish-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole hiramasa kingfish — Australia\'s premium yellowtail kingfish with rich, buttery flesh. Prized for sashimi and fine dining. Sold per kg from Tasman Star Seafoods.',
        },
        {
            name: 'Imperador Whole',
            slug: 'imperador-whole',
            price: 26.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('imperador-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole imperador — a deep-sea fish with firm white flesh and a mild, pleasant flavour. Versatile and great value, suitable for baking, grilling or steaming.',
        },
        {
            name: 'John Dory Whole',
            slug: 'john-dory-whole',
            price: 35.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('john-dory-whole.webp'), IMG('john-dory-whole-2.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole John Dory — an iconic fish with thin, delicate fillets prized by chefs worldwide. The sweet, refined flesh is perfect for pan-frying in brown butter.',
        },
        {
            name: 'Kingfish',
            slug: 'kingfish',
            price: 38.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('king-fish.webp')],
            unit: 'KG',
            tags: [],
            description: 'Kingfish — a versatile, firm-fleshed fish perfect for grilling, sashimi or ceviche. Rich in omega-3s with a clean ocean flavour. Fresh from Tasman Star Seafoods.',
        },
        {
            name: 'King George Whiting Whole',
            slug: 'king-george-whiting-whole',
            price: 42.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('king-george-whitining-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole King George whiting — widely considered Australia\'s finest eating fish with delicate, sweet white flesh. A premium species best pan-fried in butter.',
        },
        {
            name: 'King Ora Salmon Whole',
            slug: 'king-ora-salmon-whole',
            price: 38.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('king-ora-salmon-whole.webp'), IMG('salmon-whole-2.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole King Ora salmon — New Zealand\'s premium king salmon with rich, buttery flesh and vibrant colour. Ideal for roasting whole or portioning into steaks.',
        },
        {
            name: 'Local Snapper',
            slug: 'local-snapper',
            price: 35.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('local-snapper.webp'), IMG('local-snapper-whole.webp'), IMG('local-snapper-whole-2.webp')],
            unit: 'KG',
            tags: [],
            description: 'Local snapper — a Gold Coast favourite with firm, sweet flesh. Wild caught from local waters and perfect for baking, grilling or pan-frying. From Tasman Star Seafoods.',
        },
        {
            name: 'Mac Tuna Whole',
            slug: 'mac-tuna-whole',
            price: 25.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('mac-tuna-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole mac tuna — a smaller tuna species with rich, dark flesh and bold flavour. Excellent grilled or smoked. Great value from Tasman Star Seafoods.',
        },
        {
            name: 'Mixed Bin Reef Fish',
            slug: 'mixed-bin-reef-fish',
            price: 20.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('mixed-bin-reef-fish.webp')],
            unit: 'KG',
            tags: [],
            description: 'Mixed bin reef fish — a seasonal assortment of fresh reef species at great value. Perfect for families who enjoy variety. Contents vary daily at Tasman Star Seafoods.',
        },
        {
            name: 'Ocean Trout Whole',
            slug: 'ocean-trout-whole',
            price: 35.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('ocean-trout-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole ocean trout — rich, pink-fleshed fish with a buttery, delicate flavour similar to salmon. Excellent baked whole, hot-smoked or grilled.',
        },
        {
            name: 'Pearl Perch Bin',
            slug: 'pearl-perch-bin',
            price: 30.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('pearl-perch-bin.webp')],
            unit: 'KG',
            tags: [],
            description: 'Pearl perch bin — a selection of pearl perch at a competitive price. A highly regarded Queensland reef fish with sweet, moist white flesh.',
        },
        {
            name: 'Pearl Perch Whole',
            slug: 'pearl-perch-whole',
            price: 32.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('pearl-perch-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole pearl perch — one of Queensland\'s finest reef fish with moist, white flesh and a delicate, sweet flavour. Locally caught and sold per kg.',
        },
        {
            name: 'QLD Barramundi Whole',
            slug: 'qld-barramundi-whole',
            price: 25.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('qld-barra-whole.webp'), IMG('barramundi-whole-2.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole Queensland barramundi — Australia\'s iconic tropical fish with firm, white, buttery flesh. Perfect for grilling, baking or pan-frying. From Tasman Star Seafoods.',
        },
        {
            name: 'Rainbow Trout Whole',
            slug: 'rainbow-trout-whole',
            price: 35.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('rainbow-trout-whole.webp'), IMG('rainbow-trout-whole-2.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole rainbow trout — a freshwater favourite with delicate pink flesh and mild flavour. Excellent pan-fried, baked with herbs or hot-smoked.',
        },
        {
            name: 'Red Emperor Whole',
            slug: 'red-emperor-whole',
            price: 45.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('red-emperor-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole red emperor — a premium reef fish with firm, sweet white flesh. Highly prized in Asian cuisines for steaming whole. Available fresh on the Gold Coast.',
        },
        {
            name: 'Red Fish Small',
            slug: 'red-fish-small',
            price: 22.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('red-fish-small.webp')],
            unit: 'KG',
            tags: [],
            description: 'Small red fish — affordable whole fish with mild, sweet flesh. Great for pan-frying or deep-frying whole. Fresh daily from Tasman Star Seafoods.',
        },
        {
            name: 'Red Fish Whole',
            slug: 'red-fish-whole',
            price: 25.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('red-fish-whole.webp'), IMG('red-fish-whole-2.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole red fish — a versatile Australian species with firm white flesh and a clean, mild flavour. Excellent value for baking, steaming or grilling.',
        },
        {
            name: 'Red Snapper Whole',
            slug: 'red-snapper-whole',
            price: 38.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('red-snapper-whole-3.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole red snapper — a beautiful reef fish with firm, sweet flesh and striking red skin. Perfect for roasting whole or filleting. From Tasman Star Seafoods.',
        },
        {
            name: 'Sand Flounder NZ',
            slug: 'sand-flounder-nz',
            price: 22.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('sand-flounder-nz.webp')],
            unit: 'KG',
            tags: [],
            description: 'New Zealand sand flounder — a flatfish with delicate, sweet white flesh. Ideal for pan-frying whole in butter. A classic fish and chips choice.',
            countryOfOrigin: 'New Zealand',
        },
        {
            name: 'Sand Whiting Whole',
            slug: 'sand-whiting-whole',
            price: 35.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('sand-whiting-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole sand whiting — a prized Australian species with fine, sweet white flesh. One of the best eating fish available on the Gold Coast.',
        },
        {
            name: 'Sandy Sprat',
            slug: 'sandy-sprat',
            price: 12.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('sandy-sprat.webp')],
            unit: 'KG',
            tags: [],
            description: 'Sandy sprat — small, silvery fish perfect for deep-frying whole as a crispy snack or used as bait. Fresh and affordable from Tasman Star Seafoods.',
        },
        {
            name: 'School Mackerel',
            slug: 'school-mackerel',
            price: 20.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('school-mackerel.webp')],
            unit: 'KG',
            tags: [],
            description: 'School mackerel — a firm, flavourful fish rich in omega-3 fatty acids. Excellent grilled, barbecued or smoked. Great value seafood from the Gold Coast.',
        },
        {
            name: 'Flathead Whole',
            slug: 'flathead-whole',
            price: 28.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('tusky-flat-head-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole flathead — an Australian classic with sweet, white flesh that\'s perfect for fish and chips. One of the most popular eating fish in the country.',
        },
        {
            name: 'Whole Snapper',
            slug: 'whole-snapper',
            price: 35.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('whole-snap-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole snapper — a versatile, premium fish with firm, sweet flesh. Ideal for baking, steaming or grilling whole. A staple at Tasman Star Seafoods.',
        },
        {
            name: 'Yellow Fin Tuna',
            slug: 'yellow-fin-tuna',
            price: 45.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('yellow-fin-tuna-whole.webp'), IMG('yellow-fin-tuna-2.webp')],
            unit: 'KG',
            tags: [],
            description: 'Yellow fin tuna — deep red, meaty flesh prized for sashimi and searing. A premium species with clean, bold flavour. Sold per kg from Tasman Star Seafoods.',
        },
        {
            name: 'Yellow Tail Scad',
            slug: 'yellow-tail-scad',
            price: 18.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('yellow-tail-scad.webp'), IMG('yellow-tail-scad-2.webp')],
            unit: 'KG',
            tags: [],
            description: 'Yellow tail scad — a small, firm fish ideal for deep-frying whole or using as premium bait. Fresh and affordable on the Gold Coast.',
        },

        // ═══════════════════════════════════════
        // FISH (FILLETS & STEAKS)
        // ═══════════════════════════════════════
        {
            name: 'Hapuku Fillet',
            slug: 'hapuku-fillet',
            price: 48.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('harpuka-fillet.webp')],
            unit: 'KG',
            tags: [],
            description: 'Hapuku fillet — a deep-water Australian species with firm, white flesh and a clean, mild flavour. Excellent for pan-frying, roasting or grilling.',
        },
        {
            name: 'John Dory Fillets',
            slug: 'john-dory-fillets',
            price: 52.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('john-dory-fillets.webp')],
            unit: 'KG',
            tags: [],
            description: 'John Dory fillets — thin, delicate fillets with a fine, sweet flavour prized by chefs worldwide. Perfect pan-fried in brown butter. From Tasman Star Seafoods.',
        },
        {
            name: 'Mahi Mahi Fillet',
            slug: 'mahi-mahi-fillet',
            price: 38.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('mahi-mahi-fillet.webp'), IMG('mahi-mahi-fillet-2.webp'), IMG('mahi.webp')],
            unit: 'KG',
            tags: [],
            description: 'Mahi mahi fillet — firm, lean fillets with a mild, slightly sweet flavour. Excellent grilled, blackened or used in fish tacos. Sold per kg.',
        },
        {
            name: 'Ocean Trout Fillets',
            slug: 'ocean-trout-fillets',
            price: 42.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('ocean-trout-fillets.webp')],
            unit: 'KG',
            tags: [],
            description: 'Ocean trout fillets — rich, pink-fleshed fillets with a buttery, delicate flavour. Perfect for baking, grilling or serving as sashimi. From Tasman Star Seafoods.',
        },
        {
            name: 'Red Snapper Fillet',
            slug: 'red-snapper-fillet',
            price: 45.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('red-snapper-fillet.webp')],
            unit: 'KG',
            tags: [],
            description: 'Red snapper fillet — premium fillets with firm, sweet flesh and beautiful presentation. Ideal for pan-frying or baking. Fresh on the Gold Coast.',
        },
        {
            name: 'Spanish Mackerel Fillet',
            slug: 'spanish-mackerel-fillet',
            price: 35.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('spanish-mackerel-fillet.webp')],
            unit: 'KG',
            tags: [],
            description: 'Spanish mackerel fillet — a rich, full-flavoured Queensland fish with firm, oily flesh high in omega-3s. Wonderful grilled or pan-fried.',
        },
        {
            name: 'Swordfish Steak',
            slug: 'swordfish-steak',
            price: 48.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('sword-fish-steak.webp'), IMG('sword-fish-steaks.webp')],
            unit: 'KG',
            tags: [],
            description: 'Swordfish steak — thick, meaty steaks with firm, steak-like texture. Perfect on the barbecue or grill pan. Sold per kg from Tasman Star Seafoods.',
        },
        {
            name: 'Tuna Tail Cut',
            slug: 'tuna-tail-cut',
            price: 32.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('tuna-tail-cut.webp')],
            unit: 'KG',
            tags: [],
            description: 'Tuna tail cut — a leaner portion of tuna with concentrated flavour. Great value for grilling, stir-frying or braising. From Tasman Star Seafoods.',
        },

        // ═══════════════════════════════════════
        // PRAWNS (COOKED)
        // ═══════════════════════════════════════
        {
            name: 'Cooked Endeavour Prawns',
            slug: 'cooked-endeavour-prawns',
            price: 22.00,
            categorySlug: 'prawns-cooked',
            imageUrls: [IMG('cooked-endevour-prawn.webp'), IMG('ckd-endevour-prawns.webp')],
            unit: 'KG',
            tags: [],
            description: 'Cooked endeavour prawns — sweet, tender prawns with a delicate flavour. Perfect for salads, sandwiches or enjoying chilled with cocktail sauce.',
        },
        {
            name: 'Cooked School Prawns',
            slug: 'cooked-school-prawns',
            price: 18.00,
            categorySlug: 'prawns-cooked',
            imageUrls: [IMG('cooked-school-prawns.webp')],
            unit: 'KG',
            tags: [],
            description: 'Cooked school prawns — small, sweet prawns that are a Gold Coast classic. Enjoy peeled with a squeeze of lemon or tossed through pasta.',
        },
        {
            name: 'Cooked Tiger Prawns',
            slug: 'cooked-tiger-prawns',
            price: 41.00,
            categorySlug: 'prawns-cooked',
            imageUrls: [IMG('cooked-tiger-prawns-2.webp')],
            unit: 'KG',
            tags: [],
            description: 'Cooked tiger prawns — large, firm prawns with bold flavour and striking striped shells. A showstopper on any seafood platter. From Tasman Star Seafoods.',
        },
        {
            name: 'Large Cooked King Prawns',
            slug: 'large-cooked-king-prawns',
            price: 42.00,
            categorySlug: 'prawns-cooked',
            imageUrls: [IMG('large-cooked-king-prawn.webp'), IMG('large-cooked-king-prawn-1.webp'), IMG('large-cooked-king-prawn-3.webp'), IMG('large-cooked-king-prawsn.webp')],
            unit: 'KG',
            tags: [],
            description: 'Large cooked king prawns — sweet, firm and ready to serve. The centrepiece of any seafood platter. Sourced from Australian waters by Tasman Star Seafoods.',
        },
        {
            name: 'Large Cooked NQ Tiger Prawn',
            slug: 'large-cooked-nq-tiger-prawn',
            price: 40.00,
            categorySlug: 'prawns-cooked',
            imageUrls: [IMG('large-cooked-nq-tiger-prawn.webp')],
            unit: 'KG',
            tags: [],
            description: 'Large cooked North Queensland tiger prawns — premium wild-caught tigers with firm flesh and sweet, robust flavour. A top-shelf prawn for the Gold Coast.',
        },
        {
            name: 'Medium Cooked King Prawn',
            slug: 'medium-cooked-king-prawn',
            price: 32.00,
            categorySlug: 'prawns-cooked',
            imageUrls: [IMG('medium-cooked-king-prawn.webp')],
            unit: 'KG',
            tags: [],
            description: 'Medium cooked king prawns — versatile, well-priced prawns ideal for everyday meals, prawn cocktails and salads. Sold per kg from Tasman Star Seafoods.',
        },

        // ═══════════════════════════════════════
        // PRAWNS (RAW)
        // ═══════════════════════════════════════
        {
            name: 'Jumbo Raw King Prawns',
            slug: 'jumbo-raw-king-prawns',
            price: 35.00,
            categorySlug: 'prawns-raw',
            imageUrls: [IMG('jumbo-raw-kung-prawns.webp')],
            unit: 'KG',
            tags: [],
            description: 'Jumbo raw king prawns — impressively large prawns ideal for the barbecue or butterfly grilling. A premium choice from Tasman Star Seafoods.',
        },
        {
            name: 'Jumbo Raw Tiger Prawns',
            slug: 'jumbo-raw-tiger-prawns',
            price: 34.00,
            categorySlug: 'prawns-raw',
            imageUrls: [IMG('jumbo-raw-tiger-prawns.webp')],
            unit: 'KG',
            tags: [],
            description: 'Jumbo raw tiger prawns — large, bold-flavoured prawns with striking stripes. Excellent grilled, barbecued or pan-fried. Fresh on the Gold Coast.',
        },
        {
            name: 'Large Headless King Prawn',
            slug: 'large-headless-king-prawn',
            price: 28.00,
            categorySlug: 'prawns-raw',
            imageUrls: [IMG('large-headless-king-prawn.webp')],
            unit: 'KG',
            tags: [],
            description: 'Large headless king prawns — convenient and ready to cook with minimal prep. Ideal for curries, pasta dishes and stir-fries.',
        },
        {
            name: 'Large Raw NQ Tiger Prawn',
            slug: 'large-raw-nq-tiger-prawn',
            price: 32.00,
            categorySlug: 'prawns-raw',
            imageUrls: [IMG('large-raw-nq-tiger-prawn.webp'), IMG('large-raw-nq-tiger.webp')],
            unit: 'KG',
            tags: [],
            description: 'Large raw North Queensland tiger prawns — wild-caught with firm, sweet flesh. Premium quality for grilling or pan-frying. From Tasman Star Seafoods.',
        },
        {
            name: 'Mantis Prawns',
            slug: 'mantis-prawns',
            price: 25.00,
            categorySlug: 'prawns-raw',
            imageUrls: [IMG('mantis-prawns.webp')],
            unit: 'KG',
            tags: [],
            description: 'Mantis prawns — a unique crustacean with sweet, lobster-like flesh. A delicacy popular in Asian cuisines. Available fresh from Tasman Star Seafoods.',
        },
        {
            name: 'Medium Raw King Prawn',
            slug: 'medium-raw-king-prawn',
            price: 26.00,
            categorySlug: 'prawns-raw',
            imageUrls: [IMG('medium-raw-king-prawn.webp')],
            unit: 'KG',
            tags: [],
            description: 'Medium raw king prawns — a versatile, well-priced prawn perfect for curries, pasta and everyday cooking. Sold per kg.',
        },
        {
            name: 'Raw Headless King Prawn NSW',
            slug: 'raw-headless-king-prawn-nsw',
            price: 30.00,
            categorySlug: 'prawns-raw',
            imageUrls: [IMG('raw-headless-king-prawn-nsw.webp')],
            unit: 'KG',
            tags: [],
            description: 'Raw headless king prawns from NSW — premium east coast prawns with sweet, firm flesh. Ready to cook for any recipe.',
        },
        {
            name: 'Raw Prawn Cutlets',
            slug: 'raw-prawn-cutlets',
            price: 28.00,
            categorySlug: 'prawns-raw',
            imageUrls: [IMG('raw-prawn-cutlets-2.webp')],
            unit: 'KG',
            tags: [],
            description: 'Raw prawn cutlets — peeled, deveined and ready to cook. Ideal for tempura, crumbing or adding to stir-fries. Convenient and fresh.',
        },
        {
            name: 'Red Spot King Prawn Raw',
            slug: 'red-spot-king-prawn-raw',
            price: 32.00,
            categorySlug: 'prawns-raw',
            imageUrls: [IMG('red-spot-king-prawn-raw.webp')],
            unit: 'KG',
            tags: [],
            description: 'Raw red spot king prawns — a premium Australian species with distinctive markings and sweet, succulent flesh. Excellent on the barbecue.',
        },
        {
            name: 'XL Raw King Prawn',
            slug: 'xl-raw-king-prawn',
            price: 35.00,
            categorySlug: 'prawns-raw',
            imageUrls: [IMG('xl-raw-king-prawn.webp')],
            unit: 'KG',
            tags: [],
            description: 'Extra-large raw king prawns — impressive size with sweet, meaty flesh. Perfect for barbecue platters and entertaining. From Tasman Star Seafoods.',
        },

        // ═══════════════════════════════════════
        // LIVE SEAFOOD
        // ═══════════════════════════════════════
        {
            name: 'Live Mud Crabs',
            slug: 'live-mud-crabs',
            price: 60.00,
            categorySlug: 'live-seafood',
            imageUrls: [IMG('live-mud-crabs.webp')],
            unit: 'KG',
            tags: [],
            description: 'Live mud crabs — the king of Australian crabs with rich, sweet flesh. Cooked to order for the freshest possible experience. A Gold Coast favourite.',
        },
        {
            name: 'Live Spanner Crabs',
            slug: 'live-spanner-crabs',
            price: 45.00,
            categorySlug: 'live-seafood',
            imageUrls: [IMG('live-spanner-crab.webp'), IMG('live-spanner-crabs-2.webp')],
            unit: 'KG',
            tags: [],
            description: 'Live spanner crabs — a Queensland delicacy with sweet, delicate white meat. Best enjoyed steamed or boiled. Fresh from Tasman Star Seafoods.',
        },

        // ═══════════════════════════════════════
        // CRABS (COOKED)
        // ═══════════════════════════════════════
        {
            name: 'Three Spot Crab Cooked',
            slug: 'three-spot-crab-cooked',
            price: 35.00,
            categorySlug: 'crabs-cooked',
            imageUrls: [IMG('3-spot-crab-cooked.webp')],
            unit: 'KG',
            tags: [],
            description: 'Cooked three spot crab — a flavourful crab species with sweet, tender meat. Ready to crack and enjoy. Sold per kg from Tasman Star Seafoods.',
        },
        {
            name: 'Cooked and Raw Sand Crabs',
            slug: 'cooked-and-raw-sand-crabs',
            price: 30.00,
            categorySlug: 'crabs-cooked',
            imageUrls: [IMG('cooked-and-raw-sand-crabs.webp')],
            unit: 'KG',
            tags: [],
            description: 'Mixed cooked and raw sand crabs — a great value assortment for crab lovers. Sweet, delicate meat perfect for salads and sandwiches.',
        },
        {
            name: 'Cooked Local Spanner Crabs',
            slug: 'cooked-local-spanner-crabs',
            price: 55.00,
            categorySlug: 'crabs-cooked',
            imageUrls: [IMG('cooked-local-spanner-crabs.webp'), IMG('cooked-spanner-crabs-2.webp')],
            unit: 'KG',
            tags: [],
            description: 'Cooked local spanner crabs — freshly cooked Queensland spanner crabs with sweet, delicate white meat. A premium Gold Coast delicacy.',
        },
        {
            name: 'Cooked Sand Crab',
            slug: 'cooked-sand-crab',
            price: 28.00,
            categorySlug: 'crabs-cooked',
            imageUrls: [IMG('cooked-sand-crab.webp'), IMG('cooked-sand-crab-2.webp')],
            unit: 'KG',
            tags: [],
            description: 'Cooked sand crab — sweet, tender crab meat in a convenient ready-to-eat format. A popular and affordable crab option from Tasman Star Seafoods.',
        },
        {
            name: 'Mud Crab Cooked',
            slug: 'mud-crab-cooked',
            price: 65.00,
            categorySlug: 'crabs-cooked',
            imageUrls: [IMG('mud-crab-cooked.webp')],
            unit: 'KG',
            tags: [],
            description: 'Cooked mud crab — rich, sweet and succulent. Australia\'s premier crab, freshly cooked and ready to enjoy. A showpiece for any seafood feast.',
        },
        {
            name: 'Raw Sand Crabs',
            slug: 'raw-sand-crabs',
            price: 25.00,
            categorySlug: 'crabs-cooked',
            imageUrls: [IMG('raw-sand-crabs.webp'), IMG('raw-sadn.webp')],
            unit: 'KG',
            tags: [],
            description: 'Raw sand crabs — fresh and ready to cook at home. Steam or boil for the sweetest, most flavourful crab meat. Great value from Tasman Star Seafoods.',
        },
        {
            name: 'XL Cooked Spanner Crabs',
            slug: 'xl-cooked-spanner-crabs',
            price: 75.00,
            categorySlug: 'crabs-cooked',
            imageUrls: [IMG('xl-cooked-spanner-crabs.webp')],
            unit: 'KG',
            tags: [],
            description: 'Extra-large cooked spanner crabs — premium sized with generous amounts of sweet white meat. The finest spanner crabs available on the Gold Coast.',
        },

        // ═══════════════════════════════════════
        // BUGS, LOBSTERS & CRAYFISH
        // ═══════════════════════════════════════
        {
            name: 'Cooked Balmain Bugs',
            slug: 'cooked-balmain-bugs',
            price: 55.00,
            categorySlug: 'bugs-lobsters-crayfish',
            imageUrls: [IMG('cooked-balmain-bugs.webp'), IMG('cooked-balmain-bug-nsw.webp')],
            unit: 'KG',
            tags: [],
            description: 'Cooked Balmain bugs — a flat, slipper lobster with sweet, delicate meat. Ready to split and serve with butter and lemon. From Tasman Star Seafoods.',
        },
        {
            name: 'Honey Bugs',
            slug: 'honey-bugs',
            price: 65.00,
            categorySlug: 'bugs-lobsters-crayfish',
            imageUrls: [IMG('honey-bugs.webp')],
            unit: 'KG',
            tags: [],
            description: 'Honey bugs — a rare, premium Australian bug with incredibly sweet, lobster-like flesh. One of the finest crustaceans available.',
        },
        {
            name: 'Large Cooked Moreton Bay Bugs',
            slug: 'large-cooked-moreton-bay-bugs',
            price: 60.00,
            categorySlug: 'bugs-lobsters-crayfish',
            imageUrls: [IMG('large-cooked-moreton-bay-bugs.webp')],
            unit: 'KG',
            tags: [],
            description: 'Large cooked Moreton Bay bugs — a Queensland icon with sweet, firm tail meat. Perfect halved and served with garlic butter. A Gold Coast favourite.',
        },
        {
            name: 'Local Lobster Cooked',
            slug: 'local-lobster-cooked',
            price: 95.00,
            categorySlug: 'bugs-lobsters-crayfish',
            imageUrls: [IMG('local-lobster-ckd.webp')],
            unit: 'KG',
            tags: [],
            description: 'Cooked local lobster — the ultimate luxury seafood with sweet, succulent flesh. Freshly cooked and ready to serve. Premium quality from Tasman Star Seafoods.',
        },
        {
            name: 'Raw Moreton Bay Bugs',
            slug: 'raw-moreton-bay-bugs',
            price: 50.00,
            categorySlug: 'bugs-lobsters-crayfish',
            imageUrls: [IMG('raw-moreton-bay-bugs.webp')],
            unit: 'KG',
            tags: [],
            description: 'Raw Moreton Bay bugs — fresh bugs ready to split and grill or barbecue at home. The freshest way to enjoy this Queensland delicacy.',
        },
        {
            name: 'Scampi',
            slug: 'scampi',
            price: 75.00,
            categorySlug: 'bugs-lobsters-crayfish',
            imageUrls: [IMG('scampi.webp')],
            unit: 'KG',
            tags: [],
            description: 'Scampi — a deep-water crustacean with delicate, sweet flesh prized in fine dining. Excellent grilled, pan-fried or served as sashimi.',
        },
        {
            name: 'WA Crayfish Cooked',
            slug: 'wa-crayfish-cooked',
            price: 85.00,
            categorySlug: 'bugs-lobsters-crayfish',
            imageUrls: [IMG('wa-cray-fish-cooked.webp')],
            unit: 'KG',
            tags: [],
            description: 'Cooked Western Australian crayfish — also known as western rock lobster, with firm, sweet flesh. A premium centrepiece for special occasions.',
        },
        {
            name: 'WA Crayfish Live',
            slug: 'wa-crayfish-live',
            price: 90.00,
            categorySlug: 'bugs-lobsters-crayfish',
            imageUrls: [IMG('wa-cray-fish-live.webp'), IMG('wa-cray-fish-live-2.webp')],
            unit: 'KG',
            tags: [],
            description: 'Live Western Australian crayfish — the freshest possible way to enjoy this premium crustacean. Cook at home for an unforgettable dining experience.',
        },

        // ═══════════════════════════════════════
        // OYSTERS
        // ═══════════════════════════════════════
        {
            name: 'Jumbo Pacific Oyster',
            slug: 'jumbo-pacific-oyster',
            price: 30.00,
            categorySlug: 'oysters',
            imageUrls: [IMG('jumbo-pacific-oyster.webp'), IMG('jumbo-pacific-oyster-2.webp')],
            unit: 'DOZEN',
            tags: [],
            description: 'Jumbo Pacific oysters — impressively large with a clean, briny flavour and creamy texture. Serve natural with lemon or topped with kilpatrick sauce.',
        },
        {
            name: 'Oysters Kilpatrick Mornay',
            slug: 'oysters-kilpatrick-mornay',
            price: 25.00,
            categorySlug: 'oysters',
            imageUrls: [IMG('kil-patric-moynay.webp')],
            unit: 'DOZEN',
            tags: [],
            description: 'Oysters kilpatrick and mornay — prepared and ready to grill or bake. A classic Australian way to enjoy oysters. From Tasman Star Seafoods.',
        },
        {
            name: 'Oyster Opening Service',
            slug: 'oyster-opening-service',
            price: 5.00,
            categorySlug: 'oysters',
            imageUrls: [IMG('oyster-opening.webp')],
            unit: 'DOZEN',
            tags: [],
            description: 'Professional oyster opening service — have your oysters shucked and ready to serve. Add this service to any oyster purchase at Tasman Star Seafoods.',
        },
        {
            name: 'Pacific Plate Oyster',
            slug: 'pacific-plate-oyster',
            price: 22.00,
            categorySlug: 'oysters',
            imageUrls: [IMG('pacific-plate-oyster.webp'), IMG('pacific-plate-oysters.webp')],
            unit: 'DOZEN',
            tags: [],
            description: 'Pacific plate oysters — fresh, plump oysters with a clean, salty-sweet flavour. A Gold Coast staple, perfect natural or with a squeeze of lemon.',
        },

        // ═══════════════════════════════════════
        // SHELLFISH & MOLLUSCS
        // ═══════════════════════════════════════
        {
            name: 'Flame Cockles',
            slug: 'flame-cockles',
            price: 18.00,
            categorySlug: 'shellfish-molluscs',
            imageUrls: [IMG('flame-cockles-molluc.webp')],
            unit: 'KG',
            tags: [],
            description: 'Flame cockles — a colourful shellfish with sweet, tender meat. Excellent steamed with wine and garlic or added to pasta dishes.',
        },
        {
            name: 'Fresh Black Mussels',
            slug: 'fresh-black-mussels',
            price: 12.00,
            categorySlug: 'shellfish-molluscs',
            imageUrls: [IMG('fresh-black-mussels.webp')],
            unit: 'KG',
            tags: [],
            description: 'Fresh black mussels — plump, flavourful mussels perfect for steaming in white wine, garlic and herbs. Great value seafood from Tasman Star Seafoods.',
        },
        {
            name: 'Kina (Sea Urchin)',
            slug: 'kina-sea-urchin',
            price: 45.00,
            categorySlug: 'shellfish-molluscs',
            imageUrls: [IMG('kina-sea-urchin.webp')],
            unit: 'KG',
            tags: [],
            description: 'Kina (sea urchin) — a prized delicacy with rich, briny, custard-like roe. Enjoyed raw as sashimi or used to create luxurious pasta sauces.',
        },
        {
            name: 'Live Pipis',
            slug: 'live-pipis',
            price: 15.00,
            categorySlug: 'shellfish-molluscs',
            imageUrls: [IMG('live-pipis.webp'), IMG('live-pipis-2.webp')],
            unit: 'KG',
            tags: [],
            description: 'Live pipis — small, sweet Australian clams ideal for pasta vongole, chowders and steaming. Fresh and sustainably harvested.',
        },
        {
            name: 'Mixed Clams',
            slug: 'mixed-clams',
            price: 18.00,
            categorySlug: 'shellfish-molluscs',
            imageUrls: [IMG('mixed-clams.webp')],
            unit: 'KG',
            tags: [],
            description: 'Mixed clams — an assortment of fresh clam varieties perfect for steaming, pasta dishes and seafood broths. Sold per kg from Tasman Star Seafoods.',
        },
        {
            name: "Puni's Kina",
            slug: 'punis-kina',
            price: 42.00,
            categorySlug: 'shellfish-molluscs',
            imageUrls: [IMG('punits-kina.webp')],
            unit: 'KG',
            tags: [],
            description: "Puni's kina — premium grade sea urchin roe with a rich, creamy, ocean-fresh flavour. A delicacy for sashimi lovers and fine dining.",
        },
        {
            name: 'Tasmanian Scallop Meat',
            slug: 'tasmanian-scallop-meat',
            price: 40.00,
            categorySlug: 'shellfish-molluscs',
            imageUrls: [IMG('tasmania-scallops-meat.webp'), IMG('tassie-scollop-meats.webp')],
            unit: 'KG',
            tags: [],
            description: 'Tasmanian scallop meat — sweet, tender scallops from pristine Tasmanian waters. Sear in a hot pan for a golden crust. Premium quality from Tasman Star Seafoods.',
        },

        // ═══════════════════════════════════════
        // SQUID, OCTOPUS & CUTTLEFISH
        // ═══════════════════════════════════════
        {
            name: 'BBQ Octopus',
            slug: 'bbq-octopus',
            price: 22.00,
            categorySlug: 'prepared-meals',
            imageUrls: [IMG('bbq-octupus.webp')],
            unit: 'KG',
            tags: [],
            description: 'BBQ octopus — marinated and ready to grill for a smoky, charred finish. Perfect as an appetiser or added to salads. From Tasman Star Seafoods.',
        },
        {
            name: 'Clean Cuttlefish Meat',
            slug: 'clean-cuttlefish-meat',
            price: 24.00,
            categorySlug: 'squid-octopus-cuttlefish',
            imageUrls: [IMG('clean-cuttle-fish-meat.webp')],
            unit: 'KG',
            tags: [],
            description: 'Cleaned cuttlefish meat — thicker and meatier than squid with a similar mild, sweet flavour. Excellent grilled or braised in tomato sauce.',
        },
        {
            name: 'Cleaned Octopus',
            slug: 'cleaned-octopus',
            price: 25.00,
            categorySlug: 'squid-octopus-cuttlefish',
            imageUrls: [IMG('cleaned-octoupus-2.webp')],
            unit: 'KG',
            tags: [],
            description: 'Cleaned octopus — tenderised and ready to cook. Char-grill, slow-braise or roast until tender for a restaurant-quality result at home.',
        },
        {
            name: 'Fresh Local Squid',
            slug: 'fresh-local-squid',
            price: 15.00,
            categorySlug: 'squid-octopus-cuttlefish',
            imageUrls: [IMG('fresh-local-squid.webp')],
            unit: 'KG',
            tags: [],
            description: 'Fresh local squid — caught from local waters and perfect for calamari, stir-fries or stuffing. Affordable and fresh from the Gold Coast.',
        },
        {
            name: 'Local Squid Whole',
            slug: 'local-squid-whole',
            price: 14.00,
            categorySlug: 'squid-octopus-cuttlefish',
            imageUrls: [IMG('local-squid-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole local squid — uncleaned and at a great value price. Clean at home for the freshest calamari. Locally caught and sold per kg.',
        },
        {
            name: 'Marinara Mix',
            slug: 'marinara-mix',
            price: 22.00,
            categorySlug: 'prepared-meals',
            imageUrls: [IMG('marinaria-mix.webp')],
            unit: 'KG',
            tags: [],
            description: 'Marinara mix — a ready-to-cook blend of prawns, squid, mussels and fish pieces. Perfect for pasta marinara, paella or chowder. From Tasman Star Seafoods.',
        },
        {
            name: 'Seine Squid Whole',
            slug: 'seine-squid-whole',
            price: 16.00,
            categorySlug: 'squid-octopus-cuttlefish',
            imageUrls: [IMG('seine-squid-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole seine squid — a slightly larger squid variety with firm, white flesh. Ideal for cleaning and preparing as calamari rings or grilled tubes.',
        },
        {
            name: 'Southern Calamari Whole',
            slug: 'southern-calamari-whole',
            price: 20.00,
            categorySlug: 'squid-octopus-cuttlefish',
            imageUrls: [IMG('southern-calimarii-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole southern calamari — a premium Australian squid species with tender, sweet flesh. Excellent for salt and pepper calamari or grilling.',
        },
        {
            name: 'Whole Cuttlefish',
            slug: 'whole-cuttlefish',
            price: 18.00,
            categorySlug: 'squid-octopus-cuttlefish',
            imageUrls: [IMG('whole-cuttle-fish.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole cuttlefish — clean at home for the freshest cuttlefish meat. Braised in ink sauce is a classic preparation. Sold per kg from Tasman Star Seafoods.',
        },

        // ═══════════════════════════════════════
        // PREPARED MEALS
        // ═══════════════════════════════════════
        {
            name: 'Seafood Salad',
            slug: 'seafood-salad',
            price: 15.00,
            categorySlug: 'prepared-meals',
            imageUrls: [IMG('housemade-salads.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Housemade seafood salads — freshly prepared salads featuring premium seafood. A healthy, convenient lunch option from Tasman Star Seafoods.',
        },
        {
            name: 'Stir Fry Seafood Meal',
            slug: 'stir-fry-seafood-meal',
            price: 18.00,
            categorySlug: 'prepared-meals',
            imageUrls: [IMG('stir-fried-pre-made-meal.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Stir fry seafood meal — a ready-to-heat meal packed with fresh seafood and vegetables. Quick, delicious and convenient for busy weeknights.',
        },

        // ═══════════════════════════════════════
        // SUSHI
        // ═══════════════════════════════════════
        {
            name: 'Nigiri Sushi Set',
            slug: 'nigiri-sushi-set',
            price: 22.00,
            categorySlug: 'sushi',
            imageUrls: [IMG('nigiri-setsushi.webp'), IMG('sushi-nigiri-set.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Nigiri sushi set — hand-pressed sushi featuring premium fresh fish atop seasoned rice. Made fresh daily at Tasman Star Seafoods on the Gold Coast.',
        },
        {
            name: 'Sushi Platter',
            slug: 'sushi-platter',
            price: 25.00,
            categorySlug: 'sushi',
            imageUrls: [IMG('sushi.webp'), IMG('sushi-nigiri-set.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Sushi platter — an assortment of fresh sushi rolls and nigiri, beautifully presented. Perfect for sharing or a generous individual meal. From Tasman Star Seafoods.',
        },

        // ═══════════════════════════════════════
        // SASHIMI
        // ═══════════════════════════════════════
        {
            name: 'Sashimi Platter',
            slug: 'sashimi-platter',
            price: 35.00,
            categorySlug: 'sashimi',
            imageUrls: [IMG('sashimi-platter.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Sashimi platter — a premium selection of thinly sliced raw fish, beautifully arranged. Made to order with the freshest catches at Tasman Star Seafoods.',
        },

        // ═══════════════════════════════════════
        // FROZEN TRADED
        // ═══════════════════════════════════════
        {
            name: 'Baby Octopus 1kg',
            slug: 'baby-octopus-1kg',
            price: 18.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('baby-octopus-1kg.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Frozen baby octopus — tender, bite-sized octopus perfect for grilling, stir-frying or adding to salads. 1kg pack from Tasman Star Seafoods.',
        },
        {
            name: 'Blue Wave Pineapple Cut Squid Fillets',
            slug: 'blue-wave-pineapple-cut-squid-fillets',
            price: 16.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('blue-wave-raw-pineapple-cut-squid-fillets.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Blue Wave raw pineapple cut squid fillets — scored and ready to cook. Great for stir-fries, grilling or deep frying. From Tasman Star Seafoods.',
        },
        {
            name: 'Blue Wave Sliced Smoked Salmon',
            slug: 'blue-wave-sliced-smoked-salmon',
            price: 14.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('blue-wave-sliced-smoked-salmon.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Blue Wave sliced smoked salmon — premium cold-smoked salmon, thinly sliced and ready to serve. Perfect for platters, bagels and canapés.',
        },
        {
            name: 'Frozen Cooked Octopus',
            slug: 'frozen-cooked-octopus',
            price: 22.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('frozen-cooked-octopus.webp')],
            unit: 'KG',
            tags: [],
            description: 'Frozen cooked octopus — pre-cooked and ready to slice for salads, char-grill or add to pasta dishes. Convenient and full of flavour.',
        },
        {
            name: 'Frozen Lobster Meat',
            slug: 'frozen-lobster-meat',
            price: 55.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('frozen-lobster-meat.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Frozen lobster meat — premium shelled lobster meat, perfect for lobster rolls, pasta, bisques or served with butter. A luxurious treat.',
        },
        {
            name: 'Frozen Whole Octopus',
            slug: 'frozen-whole-octopus',
            price: 20.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('frozen-whole-octopus.webp')],
            unit: 'KG',
            tags: [],
            description: 'Frozen whole octopus — perfect for slow-cooking, braising or char-grilling. Tenderises beautifully when cooked low and slow.',
        },
        {
            name: 'Le Patron Salt & Pepper Squid',
            slug: 'le-patron-salt-pepper-squid',
            price: 15.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('le-patron-salt-and-pepper-squid.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Le Patron salt & pepper squid — crumbed and seasoned squid rings, ready to deep fry or air fry. A crowd-pleasing appetiser or snack.',
        },
        {
            name: "Mure's Fish Stock",
            slug: 'mures-fish-stock',
            price: 9.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('mures-fish-stock.webp')],
            unit: 'PACK',
            tags: [],
            description: "Mure's fish stock — rich, flavourful fish stock made from premium ingredients. The perfect base for seafood soups, risottos and sauces.",
        },
        {
            name: "Mure's Prawn Bisque",
            slug: 'mures-prawn-bisque',
            price: 12.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('mures-prawn-bisque.webp')],
            unit: 'PACK',
            tags: [],
            description: "Mure's prawn bisque — a rich, creamy prawn soup ready to heat and serve. Made with real prawns for an authentic restaurant-quality bisque.",
        },
        {
            name: "Mure's Smoky Fish Chowder",
            slug: 'mures-smoky-fish-chowder',
            price: 12.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('mures-smoky-fish-chowder.webp')],
            unit: 'PACK',
            tags: [],
            description: "Mure's smoky fish chowder — a hearty, smoky chowder with chunks of fish and vegetables. Heat and serve for a warming meal.",
        },
        {
            name: 'Nori Seaweed Sheets',
            slug: 'nori-seaweed-sheets',
            price: 8.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('nori-seaweed-sheets.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Nori seaweed sheets — premium roasted seaweed for sushi rolls, onigiri and snacking. Essential for any home sushi setup.',
        },
        {
            name: 'Oceanic Raw Prawn Cutlets',
            slug: 'oceanic-raw-prawn-cutlets',
            price: 16.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('oceanic-raw-prawn-cutlets.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Oceanic raw prawn cutlets — peeled, deveined and butterflied prawns ready for cooking. Ideal for tempura, stir-fries or barbecues.',
        },
        {
            name: 'Pacific West Crab Meat',
            slug: 'pacific-west-crab-meat',
            price: 12.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('pacific-west-crab-meat.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Pacific West crab meat — ready-to-use crab meat for crab cakes, salads, pasta or dips. Convenient and versatile.',
        },
        {
            name: 'Sea Gift Raw Prawns',
            slug: 'sea-gift-raw-prawns',
            price: 14.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('sea-gift-raw-prawns.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Sea Gift raw prawns — frozen raw prawns ready for your favourite recipes. Great value for everyday cooking.',
        },
        {
            name: 'Snowy Mountain Smoked Trout',
            slug: 'snowy-mountain-smoked-trout',
            price: 16.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('snowy-mountain-smoked-trout.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Snowy Mountain smoked trout — Australian smoked trout with a delicate, smoky flavour. Perfect for salads, platters or served with cream cheese.',
        },
        {
            name: 'Sockeye Salmon Fillet',
            slug: 'sockeye-salmon-fillet',
            price: 28.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('sockeye-salmon-fillet.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Sockeye salmon fillet — wild-caught sockeye salmon with deep red flesh and rich flavour. Premium quality, individually frozen for freshness.',
        },
        {
            name: 'Spring Bay Mussels',
            slug: 'spring-bay-mussels',
            price: 10.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('spring-bay-mussels.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Spring Bay mussels — Tasmanian rope-grown mussels, frozen for convenience. Steam, grill or add to pasta for a quick seafood meal.',
        },
        {
            name: 'Talleys Greenshell Mussels Chilli',
            slug: 'talleys-greenshell-mussels-chilli',
            price: 11.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('talleys-greenshell-mussels-chilli.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Talleys greenshell mussels with chilli — New Zealand half-shell mussels with a spicy chilli topping. Oven-ready in minutes.',
        },
        {
            name: 'Talleys Greenshell Mussels Cook & Go',
            slug: 'talleys-greenshell-mussels-cook-and-go',
            price: 11.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('talleys-greenshell-mussels-cook-and-go.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Talleys greenshell mussels cook & go — New Zealand half-shell mussels ready for the oven or barbecue. Quick, easy and delicious.',
        },
        {
            name: 'Talleys Greenshell Mussels Garlic',
            slug: 'talleys-greenshell-mussels-garlic',
            price: 11.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('talleys-greenshell-mussels-garlic.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Talleys greenshell mussels with garlic — New Zealand half-shell mussels with garlic butter topping. Oven-ready for an easy appetiser.',
        },
        {
            name: 'Talleys Greenshell Mussels Original',
            slug: 'talleys-greenshell-mussels-original',
            price: 10.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('talleys-greenshell-mussels-original.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Talleys greenshell mussels original — New Zealand half-shell mussels, natural and unflavoured. Steam or add to your own recipes.',
        },
        {
            name: 'Tobiko Fish Roe',
            slug: 'tobiko-fish-roe',
            price: 18.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('tobiko-fish-roe.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Tobiko fish roe — vibrant orange flying fish roe with a mild, slightly sweet flavour and satisfying pop. Essential for sushi and garnishing.',
        },

        // ═══════════════════════════════════════
        // NEW PRODUCTS — FISH (WHOLE) C1
        // ═══════════════════════════════════════
        {
            name: 'Silver Trevally Whole',
            slug: 'silver-trevally-whole',
            price: 30.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('silver-trevally-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole silver trevally — a versatile Australian fish with firm, white flesh and a mild, slightly sweet flavour. Great pan-fried, grilled or baked.',
        },
        {
            name: 'Bonito Whole',
            slug: 'bonito-whole',
            price: 25.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('bonito-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole bonito — a smaller tuna relative with rich, dark flesh and bold flavour. Excellent grilled, smoked or used for tataki.',
        },
        {
            name: 'Gurnard Whole',
            slug: 'gurnard-whole',
            price: 30.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('gurnard-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole gurnard — a striking fish with firm, sweet white flesh. Excellent roasted whole or filleted for pan-frying. From Tasman Star Seafoods.',
        },
        {
            name: 'Murray Cod Whole',
            slug: 'murray-cod-whole',
            price: 40.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('murray-cod-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole Murray cod — Australia\'s largest freshwater fish with firm, white, mild flesh. A premium native species perfect for roasting or steaming.',
        },
        {
            name: 'QLD Grouper Whole',
            slug: 'qld-grouper-whole',
            price: 40.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('qld-grouper-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole Queensland grouper — a large reef fish with firm, moist white flesh and a mild, sweet flavour. Excellent baked, steamed or grilled.',
        },
        {
            name: 'Baby Barra Whole',
            slug: 'baby-barra-whole',
            price: 20.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('baby-barra-whole.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole baby barramundi — small, tender barramundi perfect for single-serve portions. Great value and ideal for pan-frying or baking whole.',
        },
        {
            name: 'Ocean Perch Whole',
            slug: 'ocean-perch-whole',
            price: 0.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('img0821.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole ocean perch — a popular Australian fish with sweet, moist flesh. Excellent pan-fried or baked. Price set in store.',
        },
        {
            name: 'Silver Bream Whole',
            slug: 'silver-bream-whole',
            price: 0.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('img0821.webp')],
            unit: 'KG',
            tags: [],
            description: 'Whole silver bream — a mild, sweet-fleshed fish popular for pan-frying and grilling. Price set in store.',
        },
        {
            name: 'Smoked Trout',
            slug: 'smoked-trout',
            price: 18.00,
            categorySlug: 'fish-whole',
            imageUrls: [IMG('snowy-mountain-smoked-trout.webp')],
            unit: 'KG',
            tags: [],
            description: 'Smoked trout — delicately smoked whole trout with a rich, smoky flavour. Perfect for salads, platters or enjoying on its own.',
        },

        // ═══════════════════════════════════════
        // NEW PRODUCTS — FISH (FILLETS & STEAKS) C2
        // ═══════════════════════════════════════
        {
            name: 'Gold Band Snapper Fillet',
            slug: 'gold-band-snapper-fillet',
            price: 65.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('img0907.webp')],
            unit: 'KG',
            tags: [],
            description: 'Gold band snapper fillet — premium deep-water snapper with firm, moist flesh and delicate flavour. Excellent pan-fried or baked.',
        },
        {
            name: 'Local Snapper Fillet',
            slug: 'local-snapper-fillet',
            price: 65.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('local-snapper-fillet.webp')],
            unit: 'KG',
            tags: [],
            description: 'Local snapper fillet — wild-caught snapper filleted fresh daily. Sweet, firm flesh perfect for pan-frying or baking.',
        },
        {
            name: 'Tuna Steak',
            slug: 'tuna-steak',
            price: 55.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('img5217.webp')],
            unit: 'KG',
            tags: [],
            description: 'Tuna steak — thick-cut tuna with deep red flesh. Best seared rare to medium-rare for maximum flavour. Premium quality from Tasman Star Seafoods.',
        },
        {
            name: 'Monkfish Fillet',
            slug: 'monkfish-fillet',
            price: 45.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('monkfish-fillet.webp')],
            unit: 'KG',
            tags: [],
            description: 'Monkfish fillet — known as "poor man\'s lobster" for its firm, sweet, lobster-like flesh. Excellent roasted, grilled or wrapped in prosciutto.',
        },
        {
            name: 'Gurnard Fillet',
            slug: 'gurnard-fillet',
            price: 50.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('img2266.webp')],
            unit: 'KG',
            tags: [],
            description: 'Gurnard fillet — sweet, firm white fillets from this striking fish. Excellent pan-fried with butter and capers.',
        },
        {
            name: 'Salon Barramundi Fillet',
            slug: 'salon-barramundi-fillet',
            price: 45.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('img0866.webp')],
            unit: 'KG',
            tags: [],
            description: 'Salon (farmed) barramundi fillet — consistently high quality with firm, white, buttery flesh. A versatile everyday fish perfect for any cooking method.',
        },
        {
            name: 'Wild Barramundi Fillet',
            slug: 'wild-barramundi-fillet',
            price: 70.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('img1949.webp')],
            unit: 'KG',
            tags: [],
            description: 'Wild barramundi fillet — wild-caught with a cleaner, more complex flavour than farmed. Premium quality from Australian waters.',
        },
        {
            name: 'Mangrove Jack Fillet',
            slug: 'mangrove-jack-fillet',
            price: 50.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('img5446.webp')],
            unit: 'KG',
            tags: [],
            description: 'Mangrove jack fillet — a tropical species with firm, sweet white flesh. Popular in Asian cuisines, excellent pan-fried or steamed.',
        },
        {
            name: 'Mackerel Cutlets',
            slug: 'mackerel-cutlets',
            price: 45.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('img6680.webp')],
            unit: 'KG',
            tags: [],
            description: 'Mackerel cutlets — thick, meaty cutlets rich in omega-3s. Excellent on the barbecue or grilled with lemon and herbs.',
        },
        {
            name: 'Salmon Sides',
            slug: 'salmon-sides',
            price: 50.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('img0821.webp')],
            unit: 'KG',
            tags: [],
            description: 'Salmon sides — whole side of premium salmon, perfect for baking, curing or slicing into portions. Great for entertaining.',
        },
        {
            name: 'Salmon Portions',
            slug: 'salmon-portions',
            price: 55.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('salmon-portions.webp')],
            unit: 'KG',
            tags: [],
            description: 'Salmon portions — individually portioned premium salmon fillets. Convenient and ready to cook for a quick, healthy meal.',
        },
        {
            name: 'Barra Fillet',
            slug: 'barra-fillet',
            price: 50.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('barra-fillet.webp')],
            unit: 'KG',
            tags: [],
            description: 'Barramundi fillet — Australia\'s most popular fish with firm, white, buttery flesh. Versatile and perfect for any cooking method.',
        },
        {
            name: 'Barra Sides',
            slug: 'barra-sides',
            price: 45.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('img5402.webp')],
            unit: 'KG',
            tags: [],
            description: 'Barramundi sides — whole side of barramundi for baking, grilling or portioning at home. Great value for families.',
        },
        {
            name: 'Coral Trout Fillet',
            slug: 'coral-trout-fillet',
            price: 120.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('coral-trout-fillet.webp')],
            unit: 'KG',
            tags: [],
            description: 'Coral trout fillet — Queensland\'s most prized reef fish fillet with delicate, sweet white flesh. Ultra-premium quality for special occasions.',
        },
        {
            name: 'Flathead Fillet',
            slug: 'flathead-fillet',
            price: 65.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('flathead-fillet.webp')],
            unit: 'KG',
            tags: [],
            description: 'Flathead fillet — Australia\'s favourite fish for fish and chips. Sweet, white flesh with a delicate texture. Filleted fresh daily.',
        },
        {
            name: 'Ling Fillet',
            slug: 'ling-fillet',
            price: 50.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('ling-fillet.webp')],
            unit: 'KG',
            tags: [],
            description: 'Ling fillet — a deep-water fish with firm, white flesh and a mild flavour. Excellent for fish and chips, baking or grilling.',
        },
        {
            name: 'Jewfish Fillet',
            slug: 'jewfish-fillet',
            price: 50.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('jewfish-fillet.webp')],
            unit: 'KG',
            tags: [],
            description: 'Jewfish fillet — also known as mulloway, with firm, white flesh and a mild, sweet flavour. A premium Australian species.',
        },
        {
            name: 'Sockeye Salmon Fillet (Fresh)',
            slug: 'sockeye-salmon-fillet-fresh',
            price: 28.00,
            categorySlug: 'fish-fillets-steaks',
            imageUrls: [IMG('sockeye-salmon-fillet.webp')],
            unit: 'KG',
            tags: [],
            description: 'Fresh sockeye salmon fillet — wild-caught with deep red flesh and rich, bold flavour. Premium quality, perfect for grilling or baking.',
        },

        // ═══════════════════════════════════════
        // NEW PRODUCTS — PRAWNS (COOKED) C3
        // ═══════════════════════════════════════
        {
            name: 'Jumbo Cooked King Prawns',
            slug: 'jumbo-cooked-king-prawns',
            price: 42.00,
            categorySlug: 'prawns-cooked',
            imageUrls: [IMG('img4908.webp')],
            unit: 'KG',
            tags: [],
            description: 'Jumbo cooked king prawns — extra-large, sweet and succulent. The ultimate centrepiece for any seafood platter.',
        },

        // ═══════════════════════════════════════
        // NEW PRODUCTS — PRAWNS (RAW) C4
        // ═══════════════════════════════════════
        {
            name: 'Prawn Meat',
            slug: 'prawn-meat',
            price: 30.00,
            categorySlug: 'prawns-raw',
            imageUrls: [IMG('img0314.webp')],
            unit: 'KG',
            tags: [],
            description: 'Raw prawn meat — peeled, deveined and ready to cook. Perfect for stir-fries, curries, pasta and dumplings.',
        },
        {
            name: 'Garlic Prawns',
            slug: 'garlic-prawns',
            price: 28.00,
            categorySlug: 'prawns-raw',
            imageUrls: [IMG('img5525.webp')],
            unit: 'KG',
            tags: [],
            description: 'Garlic prawns — marinated in garlic butter and ready to cook. A classic Australian favourite, just heat and serve.',
        },

        // ═══════════════════════════════════════
        // NEW PRODUCTS — OYSTERS C5
        // ═══════════════════════════════════════
        {
            name: 'Sydney Rock Plate Oysters',
            slug: 'sydney-rock-plate-oysters',
            price: 35.00,
            categorySlug: 'oysters',
            imageUrls: [IMG('img0362.webp')],
            unit: 'DOZEN',
            tags: [],
            description: 'Sydney Rock plate oysters — Australia\'s native oyster with a rich, complex mineral flavour. Shucked and served on a plate, ready to enjoy.',
        },
        {
            name: 'Sydney Rock Bistro Oysters',
            slug: 'sydney-rock-bistro-oysters',
            price: 30.00,
            categorySlug: 'oysters',
            imageUrls: [IMG('img0362.webp')],
            unit: 'DOZEN',
            tags: [],
            description: 'Sydney Rock bistro oysters — slightly smaller rocks with the same rich, mineral flavour. Great value for cooking or natural enjoyment.',
        },
        {
            name: 'Sydney Rock Cocktail Oysters',
            slug: 'sydney-rock-cocktail-oysters',
            price: 25.00,
            categorySlug: 'oysters',
            imageUrls: [IMG('img0362.webp')],
            unit: 'DOZEN',
            tags: [],
            description: 'Sydney Rock cocktail oysters — petite-sized rocks perfect for Kilpatrick, shooters or canapés. Great value.',
        },
        {
            name: 'Live Unshucked Oysters',
            slug: 'live-unshucked-oysters',
            price: 25.00,
            categorySlug: 'oysters',
            imageUrls: [IMG('live-unshucked-oysters.webp')],
            unit: 'DOZEN',
            tags: [],
            description: 'Live unshucked oysters — the freshest way to enjoy oysters. Shuck at home for a true ocean-to-plate experience.',
        },
        {
            name: 'Oyster Vinaigrette',
            slug: 'oyster-vinaigrette',
            price: 3.00,
            categorySlug: 'oysters',
            imageUrls: [IMG('img0362.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Oyster vinaigrette — a classic French-style accompaniment for raw oysters. Adds a bright, tangy contrast to fresh oysters.',
        },

        // ═══════════════════════════════════════
        // NEW PRODUCTS — SHELLFISH & MOLLUSCS C6
        // ═══════════════════════════════════════
        {
            name: 'Roe Off Scallop',
            slug: 'roe-off-scallop',
            price: 90.00,
            categorySlug: 'shellfish-molluscs',
            imageUrls: [IMG('img0861.webp')],
            unit: 'KG',
            tags: [],
            description: 'Roe off scallop — premium scallop meat without the roe. Sweet, tender and perfect for searing to a golden crust.',
        },
        {
            name: 'Mussel Pack 1kg',
            slug: 'mussel-pack-1kg',
            price: 19.00,
            categorySlug: 'shellfish-molluscs',
            imageUrls: [IMG('fresh-black-mussels.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Fresh mussel pack — 1kg of plump, flavourful mussels ready for steaming in white wine, garlic and herbs.',
        },
        {
            name: 'Cooked Vongole Pack 1kg',
            slug: 'cooked-vongole-pack-1kg',
            price: 40.00,
            categorySlug: 'shellfish-molluscs',
            imageUrls: [IMG('img4822.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Cooked vongole — pre-cooked clams ready to toss through pasta or enjoy in a broth. 1kg pack for convenience.',
        },
        {
            name: 'Greenlip Mussels Half Shell',
            slug: 'greenlip-mussels-half-shell',
            price: 25.00,
            categorySlug: 'shellfish-molluscs',
            imageUrls: [IMG('img1343.webp')],
            unit: 'KG',
            tags: [],
            description: 'Greenlip mussels on half shell — New Zealand greenshell mussels, perfect for grilling with garlic butter or baking.',
        },
        {
            name: 'Greenlip Mussels Whole Shell',
            slug: 'greenlip-mussels-whole-shell',
            price: 19.00,
            categorySlug: 'shellfish-molluscs',
            imageUrls: [IMG('img1343.webp')],
            unit: 'KG',
            tags: [],
            description: 'Greenlip mussels in whole shell — steam, grill or add to pasta for a flavourful New Zealand mussel experience.',
        },
        {
            name: 'Greenlip Mussel Meat',
            slug: 'greenlip-mussel-meat',
            price: 35.00,
            categorySlug: 'shellfish-molluscs',
            imageUrls: [IMG('img1343.webp')],
            unit: 'KG',
            tags: [],
            description: 'Greenlip mussel meat — shelled New Zealand mussel meat, ready to add to chowders, pasta or stir-fries.',
        },
        {
            name: 'Cooked Greenlip Half Shell',
            slug: 'cooked-greenlip-half-shell',
            price: 25.00,
            categorySlug: 'shellfish-molluscs',
            imageUrls: [IMG('img1343.webp')],
            unit: 'KG',
            tags: [],
            description: 'Cooked greenlip mussels on half shell — pre-cooked and ready to serve. Just heat through for a quick, impressive appetiser.',
        },
        {
            name: 'Mussel Pots',
            slug: 'mussel-pots',
            price: 12.00,
            categorySlug: 'shellfish-molluscs',
            imageUrls: [IMG('img3372.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Mussel pots — individual ready-to-heat mussel pots with sauce. A convenient, restaurant-quality mussel dish at home.',
        },

        // ═══════════════════════════════════════
        // NEW PRODUCTS — BUGS, LOBSTERS & CRAYFISH C7
        // ═══════════════════════════════════════
        {
            name: 'Live Local Lobsters',
            slug: 'live-local-lobsters',
            price: 95.00,
            categorySlug: 'bugs-lobsters-crayfish',
            imageUrls: [IMG('img1424.webp')],
            unit: 'KG',
            tags: [],
            description: 'Live local lobsters — the freshest lobster experience. Cook at home for the most flavourful, succulent lobster.',
        },
        {
            name: 'Lobster Tails',
            slug: 'lobster-tails',
            price: 90.00,
            categorySlug: 'bugs-lobsters-crayfish',
            imageUrls: [IMG('img6426.webp')],
            unit: 'KG',
            tags: [],
            description: 'Lobster tails — premium tails perfect for grilling, baking or butterflying. Sweet, succulent lobster meat.',
        },
        {
            name: 'Lobster Mornay',
            slug: 'lobster-mornay',
            price: 45.00,
            categorySlug: 'bugs-lobsters-crayfish',
            imageUrls: [IMG('img1424.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Lobster mornay — lobster prepared in a rich, creamy cheese sauce. A classic Australian seafood dish, ready to bake.',
        },
        {
            name: 'Bug Meat',
            slug: 'bug-meat',
            price: 65.00,
            categorySlug: 'bugs-lobsters-crayfish',
            imageUrls: [IMG('img1344.webp')],
            unit: 'KG',
            tags: [],
            description: 'Bug meat — shelled Moreton Bay bug tail meat. Sweet, delicate and ready for your favourite recipe.',
        },
        {
            name: 'Cooked Crabs',
            slug: 'cooked-crabs',
            price: 30.00,
            categorySlug: 'bugs-lobsters-crayfish',
            imageUrls: [IMG('img6849.webp')],
            unit: 'KG',
            tags: [],
            description: 'Cooked crabs — freshly cooked and ready to crack. Sweet, tender crab meat for platters, salads or sandwiches.',
        },
        {
            name: 'King Crab Clusters',
            slug: 'king-crab-clusters',
            price: 85.00,
            categorySlug: 'bugs-lobsters-crayfish',
            imageUrls: [IMG('img6849.webp')],
            unit: 'KG',
            tags: [],
            description: 'King crab clusters — impressive, meaty crab legs with sweet, succulent flesh. A showstopper for special occasions.',
        },
        {
            name: 'Crab Meat Jar',
            slug: 'crab-meat-jar',
            price: 25.00,
            categorySlug: 'bugs-lobsters-crayfish',
            imageUrls: [IMG('img6849.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Crab meat jar — ready-to-use crab meat perfect for crab cakes, salads, dips and sandwiches.',
        },

        // ═══════════════════════════════════════
        // NEW PRODUCTS — SQUID, OCTOPUS & CUTTLEFISH C8
        // ═══════════════════════════════════════
        {
            name: 'Baby Octopus',
            slug: 'baby-octopus',
            price: 20.00,
            categorySlug: 'squid-octopus-cuttlefish',
            imageUrls: [IMG('img5293.webp')],
            unit: 'KG',
            tags: [],
            description: 'Fresh baby octopus — tender, bite-sized octopus perfect for char-grilling, stir-frying or adding to salads.',
        },
        {
            name: 'Large Octopus',
            slug: 'large-octopus',
            price: 25.00,
            categorySlug: 'squid-octopus-cuttlefish',
            imageUrls: [IMG('img5334.webp')],
            unit: 'KG',
            tags: [],
            description: 'Large octopus — great for slow-cooking, braising or char-grilling. Tenderises beautifully when cooked low and slow.',
        },

        // ═══════════════════════════════════════
        // NEW PRODUCTS — FROZEN TRADED C9
        // ═══════════════════════════════════════
        {
            name: '1kg Roe Off Scallop (Frozen)',
            slug: 'frozen-roe-off-scallop-1kg',
            price: 45.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('img5571.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Frozen roe off scallop — 1kg pack of premium scallop meat without roe. Ready to thaw and sear for a restaurant-quality dish.',
        },
        {
            name: '500g Spanner Meat Packs',
            slug: 'frozen-spanner-meat-packs',
            price: 35.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('cooked-spanner-crabs-2.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Frozen spanner crab meat — 500g packs of sweet, delicate spanner crab meat. Convenient for crab rolls, salads and pasta.',
        },
        {
            name: 'Frozen Lobster Tails',
            slug: 'frozen-lobster-tails',
            price: 55.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('img6426.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Frozen lobster tails — premium lobster tails, individually frozen for freshness. Perfect for a special dinner at home.',
        },
        {
            name: '5kg Large Cooked King Prawn Box',
            slug: 'frozen-5kg-cooked-king-box',
            price: 180.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('img6063.webp')],
            unit: 'BOX',
            tags: [],
            description: '5kg box of large cooked king prawns — bulk value for events, parties and large gatherings. Premium quality.',
        },
        {
            name: '5kg Raw Large Tiger Prawn Box',
            slug: 'frozen-5kg-raw-tiger-box',
            price: 160.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('img2265.webp')],
            unit: 'BOX',
            tags: [],
            description: '5kg box of raw large tiger prawns — bulk value for restaurants, events and serious prawn lovers.',
        },
        {
            name: 'WA Crayfish Cooked (Frozen)',
            slug: 'wa-crayfish-cooked-frozen',
            price: 75.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('wa-cray-fish-cooked.webp')],
            unit: 'KG',
            tags: [],
            description: 'Frozen cooked WA crayfish — premium Western Australian crayfish, flash-frozen for convenience. Just thaw and enjoy.',
        },
        {
            name: 'Squid Tubes (Frozen)',
            slug: 'frozen-squid-tubes',
            price: 18.00,
            categorySlug: 'frozen-traded',
            imageUrls: [IMG('img2284.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Frozen squid tubes — cleaned and ready for stuffing, grilling or slicing into calamari rings. Convenient and versatile.',
        },

        // ═══════════════════════════════════════
        // NEW PRODUCTS — SAUCES, CONDIMENTS & PACKAGED GOODS C10
        // ═══════════════════════════════════════
        {
            name: 'Cocktail Sauce (Small)',
            slug: 'cocktail-sauce-small',
            price: 4.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('img3304.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Cocktail sauce — classic seafood dipping sauce in a convenient single-serve size. Perfect with prawns and oysters.',
        },
        {
            name: 'Tartare Sauce (Small)',
            slug: 'tartare-sauce-small',
            price: 4.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('img3304.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Tartare sauce — creamy, tangy sauce perfect with battered fish and seafood. Single-serve size.',
        },
        {
            name: 'Garlic Aioli (Small)',
            slug: 'garlic-aioli-small',
            price: 4.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('img3304.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Garlic aioli — rich, garlicky dipping sauce perfect with seafood, chips and platters. Single-serve size.',
        },
        {
            name: 'Sweet Soy Sauce (Small)',
            slug: 'sweet-soy-sauce-small',
            price: 4.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('img3304.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Sweet soy sauce — a rich, sweet soy dipping sauce ideal for sushi, sashimi and Asian seafood dishes.',
        },
        {
            name: 'Cocktail Sauce (Bottle)',
            slug: 'cocktail-sauce-bottle',
            price: 8.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('img3304.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Cocktail sauce bottle — classic seafood dipping sauce in a family-sized bottle for entertaining.',
        },
        {
            name: 'Tartare Sauce (Bottle)',
            slug: 'tartare-sauce-bottle',
            price: 8.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('img3304.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Tartare sauce bottle — creamy tartare sauce in a family-sized bottle. A pantry staple for seafood lovers.',
        },
        {
            name: 'Sriracha Mayo',
            slug: 'sriracha-mayo',
            price: 8.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('img3304.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Sriracha mayo — spicy, creamy sauce perfect with fish tacos, sushi bowls and fried seafood.',
        },
        {
            name: 'Japanese Mayo',
            slug: 'japanese-mayo',
            price: 8.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('img3304.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Japanese mayo — rich, creamy Kewpie-style mayo. Essential for sushi, takoyaki and okonomiyaki.',
        },
        {
            name: 'Ranch Sauce',
            slug: 'ranch-sauce',
            price: 8.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('img3304.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Ranch sauce — creamy, herby dipping sauce that pairs perfectly with fried seafood and chips.',
        },
        {
            name: 'Chilli Mussel Cooking Sauce',
            slug: 'chilli-mussel-cooking-sauce',
            price: 10.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('img3304.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Chilli mussel cooking sauce — a flavourful sauce ready for steaming mussels. Just add mussels and heat.',
        },
        {
            name: 'Marinara Cooking Sauce',
            slug: 'marinara-cooking-sauce',
            price: 10.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('img3304.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Marinara cooking sauce — a rich tomato-based sauce perfect for pasta marinara with your favourite seafood mix.',
        },
        {
            name: 'Green Curry Cooking Sauce',
            slug: 'green-curry-cooking-sauce',
            price: 10.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('img3304.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Green curry cooking sauce — aromatic Thai-style green curry sauce. Add seafood and coconut cream for a quick curry.',
        },
        {
            name: 'Red Curry Cooking Sauce',
            slug: 'red-curry-cooking-sauce',
            price: 10.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('img3304.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Red curry cooking sauce — rich Thai-style red curry sauce. Perfect with prawns, fish or mixed seafood.',
        },
        {
            name: 'Sardine Fillets (Packaged)',
            slug: 'sardine-fillets-packaged',
            price: 8.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('img4817.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Sardine fillets — premium canned sardine fillets in oil. Great for sandwiches, pasta or enjoying straight from the tin.',
        },
        {
            name: 'Sardine Trunks (Packaged)',
            slug: 'sardine-trunks-packaged',
            price: 8.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('img4817.webp')],
            unit: 'PACK',
            tags: [],
            description: 'Sardine trunks — whole sardines packed in oil. A nutritious, affordable snack rich in omega-3s.',
        },
        {
            name: '200g Smoked Salmon Trays',
            slug: 'smoked-salmon-trays-200g',
            price: 14.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('blue-wave-sliced-smoked-salmon.webp')],
            unit: 'PACK',
            tags: [],
            description: '200g smoked salmon trays — premium sliced smoked salmon, perfect for platters, bagels and canapés.',
        },
        {
            name: 'Marinated Octopus Pots',
            slug: 'marinated-octopus-pots',
            price: 12.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('img5334.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Marinated octopus pots — tender octopus in a flavourful marinade. Ready to serve as a tapas-style appetiser.',
        },
        {
            name: 'Marinated Sardine Pots',
            slug: 'marinated-sardine-pots',
            price: 10.00,
            categorySlug: 'sauces-condiments-packaged',
            imageUrls: [IMG('img4817.webp')],
            unit: 'PIECE',
            tags: [],
            description: 'Marinated sardine pots — sardines in a zesty marinade. A delicious, healthy snack or antipasto addition.',
        },
    ];

    console.log(`Seeding ${products.length} products...`);

    for (const product of products) {
        const { categorySlug, ...productData } = product;
        const created = await prisma.product.create({
            data: {
                ...productData,
                stockQuantity: Math.floor(Math.random() * 50) + 10,
                isAvailable: true,
            },
        });
        await prisma.productCategory.create({
            data: {
                productId: created.id,
                categoryId: categoryMap[categorySlug],
                isPrimary: true,
            },
        });
    }
    console.log(`Created ${products.length} products`);

    // ── Delete and recreate Wholesale Categories & Sample Items ──
    await prisma.wholesaleOrderItem.deleteMany({});
    await prisma.wholesaleOrder.deleteMany({});
    await prisma.wholesalePriceItem.deleteMany({});
    await prisma.wholesaleCategory.deleteMany({});

    const wholesaleCategories = [
        { name: 'Prawns', sortOrder: 1 },
        { name: 'Fish Fillets', sortOrder: 2 },
        { name: 'Crabs & Lobsters', sortOrder: 3 },
        { name: 'Shellfish', sortOrder: 4 },
        { name: 'Whole Fish', sortOrder: 5 },
    ];

    const wsCategoryMap: Record<string, string> = {};
    for (const cat of wholesaleCategories) {
        const created = await prisma.wholesaleCategory.create({
            data: cat,
        });
        wsCategoryMap[cat.name] = created.id;
    }

    const wholesaleItems = [
        { name: 'Tiger Prawns U8-12', unit: 'per kg', price: 22.00, categoryName: 'Prawns' },
        { name: 'Tiger Prawns U15-20', unit: 'per kg', price: 18.50, categoryName: 'Prawns' },
        { name: 'Banana Prawns (cooked)', unit: 'per kg', price: 19.00, categoryName: 'Prawns' },
        { name: 'King Prawns Raw', unit: 'per 5kg box', price: 85.00, categoryName: 'Prawns' },
        { name: 'Barramundi Fillets', unit: 'per kg', price: 32.00, categoryName: 'Fish Fillets' },
        { name: 'Salmon Atlantic Fillets', unit: 'per kg', price: 38.00, categoryName: 'Fish Fillets' },
        { name: 'Blue Eye Cod Fillets', unit: 'per kg', price: 55.00, categoryName: 'Fish Fillets' },
        { name: 'Snapper Fillets', unit: 'per kg', price: 28.00, categoryName: 'Fish Fillets' },
        { name: 'Mud Crab Live', unit: 'per kg', price: 48.00, categoryName: 'Crabs & Lobsters' },
        { name: 'Spanner Crab Meat', unit: 'per kg', price: 65.00, categoryName: 'Crabs & Lobsters' },
        { name: 'Moreton Bay Bugs', unit: 'per kg', price: 42.00, categoryName: 'Crabs & Lobsters' },
        { name: 'Scallops (roe off)', unit: 'per kg', price: 45.00, categoryName: 'Shellfish' },
        { name: 'Oysters Pacific Dozen', unit: 'per dozen', price: 12.00, categoryName: 'Shellfish' },
        { name: 'Whole Snapper', unit: 'per kg', price: 18.00, categoryName: 'Whole Fish' },
        { name: 'Whole Barramundi', unit: 'per kg', price: 22.00, categoryName: 'Whole Fish' },
    ];

    for (const item of wholesaleItems) {
        const { categoryName, ...itemData } = item;
        await prisma.wholesalePriceItem.create({
            data: {
                ...itemData,
                categoryId: wsCategoryMap[categoryName],
                isAvailable: true,
            },
        });
    }
    console.log(`Created ${wholesaleItems.length} wholesale price items`);

    console.log('Seeding complete!');
}

main()
    .then(async () => {
        await prisma.$disconnect();
    })
    .catch(async (e) => {
        console.error(e);
        await prisma.$disconnect();
        process.exit(1);
    });
